# Generated by Django 6.0.4 on 2026-04-24 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('draw_id', models.BigIntegerField(db_index=True)),
                ('draw_winner_id', models.BigIntegerField(blank=True, null=True)),
                ('match_type', models.CharField(max_length=20)),
                ('prize_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='winner_proofs/')),
                ('proof_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('reviewed_by', models.BigIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True, null=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'dh_winner_verifications',
            },
        ),
    ]
