# Generated by Django 6.0.4 on 2026-04-24 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('draw_type', models.CharField(choices=[('random', 'Random'), ('algorithmic', 'Algorithmic')], default='random', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('simulated', 'Simulated'), ('published', 'Published')], default='draft', max_length=20)),
                ('draw_month', models.IntegerField()),
                ('draw_year', models.IntegerField()),
                ('winning_numbers', models.JSONField(blank=True, null=True)),
                ('prize_pool_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('jackpot_rollover', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('jackpot_claimed', models.BooleanField(default=False)),
                ('published_by', models.BigIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('simulation_data', models.JSONField(blank=True, null=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DrawParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_id', models.BigIntegerField(db_index=True)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('submitted_scores', models.JSONField()),
                ('matched_count', models.IntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DrawWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_id', models.BigIntegerField(db_index=True)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('match_type', models.CharField(choices=[('5_match', '5 Match'), ('4_match', '4 Match'), ('3_match', '3 Match')], max_length=20)),
                ('prize_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
